1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [2]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


2. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49.

In [4]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. create two arrays and stack them vertically

In [5]:
b=np.random.randint(1,10,(2,2))
c=np.random.randint(11,22,(3,2))
d=np.vstack((b,c))
print(d)

[[ 4  6]
 [ 6  7]
 [15 14]
 [18 18]
 [13 12]]


5. Reverse a vector (first element becomes last).

In [19]:
e=np.arange(1,10)
f=np.flip(e)
print(e)
print(f)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
g=np.arange(0,9)
print(g)
g=np.reshape(g,(3,3))
print(g)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Find indices of non-zero elements from [1,2,0,0,4,0]

In [35]:
h=[1,2,0,0,4,0]
print("index of non zero element = ", end="")
for index,value in enumerate(h):
    if value!=0:
        print(index, end=",")

index of non zero element = 0,1,4,

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [43]:
k=np.random.randint(1,50,(10,10))
print(k)
print("max = ",np.amax(k))
print("min = ",np.amin(k))

[[40 45 46 34 14  3 42 21 18 46]
 [18 10 24 47 13 44  9 22 30  3]
 [ 4  5 22 15 38 42 17  1 36 48]
 [ 7  1 28  2 49  7 30 25 12 15]
 [13 36  8 31 36  8  1 10  8 44]
 [28 31 14 45 11 31 43 34 27 18]
 [15 27 32 48  6 13  7 10 47 20]
 [ 2 27 32 38 26 48  8 37 24 26]
 [ 4 19 49 37 41 27 28 26 46 11]
 [ 6 26 43 31 39 42 10  7 39 29]]
max =  49
min =  1


9. Create a random vector of size 30 and find the mean value.

In [37]:
i=np.arange(1,31)
print(i)
print(np.mean(i))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
15.5


10. Create a 2d array with 1 on the border and 0 inside


In [53]:
j=np.ones((5,5))
print(j)

j[1:-1,1:-1]=0
print(j)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


11. How to add a border (filled with 0's) around an existing array

In [60]:
k=np.ones((5,5))
np.pad(k, (1,1), mode = 'constant')

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

12. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [63]:
l=np.zeros((5,5))
for i in range(1,5):
    l[i][i-1]=i
print(l)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


13. Create a 5*5 matrix with random values and normalize it.

In [3]:
import numpy as np

m = np.random.random((5,5))
n= (a - a.min())/(a.max()-a.min())
print(n)


[[0.79121853 0.78027614 0.26472897 0.82594969 0.54057746]
 [0.33775101 0.74658721 0.70013936 0.70670109 1.        ]
 [0.12266251 0.75876861 0.94437459 0.5754496  0.1376047 ]
 [0.18370434 0.41257724 0.         0.8030731  0.69388355]
 [0.76399272 0.78996531 0.21147197 0.09702802 0.3606453 ]]


14. How to find common values between two arrays

In [11]:
o=np.random.randint(1,21,(5,10))
p=np.random.randint(1,21,(5,10))
print(o)
print()
print(p, "\n")
print("common values ", np.intersect1d(o,p))

[[ 4 19  1  7  8 19 11  3 11 12]
 [12 15  5 20  8 18 15 10 15 18]
 [ 9 20  6  5 15  6  2 17  4  7]
 [ 8  9 13 15 14  7  3 12 18 13]
 [12 16 11 11 20 18  4 18 11 15]]

[[12 10  7 19  7 20 12 15  2 15]
 [20 14  7 12  6  1 16  9  9 18]
 [11 15 19  7 11 11 17  7  7 20]
 [16  4 18  4 17 20 15 15 17 16]
 [ 3 13 16  7 11 18 17  1 11 15]] 

common values  [ 1  2  3  4  6  7  9 10 11 12 13 14 15 16 17 18 19 20]


15. Consider a generator function that generates 10 integers and use it to build an array

In [12]:
def generator():
    q = np.array(np.arange(10))
    return q

print(generator())

[0 1 2 3 4 5 6 7 8 9]


16. Subtract the mean of each row of a matrix

In [43]:
r = np.random.random((10,5))
print(r, "\n")
means = np.mean(r, axis = 1)
print("means= ", means, "\n")
for i in range(r.shape[0]):
    arr[i]=arr[i]-means[i]
print("array after mean ", r)    

[[0.83925279 0.56811061 0.76086462 0.15980631 0.71178566]
 [0.90192488 0.77950678 0.80074812 0.11522967 0.76371438]
 [0.61653176 0.53831009 0.5015355  0.00733768 0.79626574]
 [0.98553605 0.99392451 0.13801976 0.14372778 0.89701369]
 [0.7190047  0.74636379 0.23667757 0.09398866 0.33174383]
 [0.49876342 0.08404513 0.80357209 0.67052543 0.67306425]
 [0.6491193  0.53799825 0.55256675 0.13415758 0.41726345]
 [0.95632547 0.09117056 0.77600815 0.55150046 0.8640254 ]
 [0.71720482 0.26171909 0.66812968 0.01033446 0.97945504]
 [0.40814974 0.26823001 0.16871806 0.33874824 0.617842  ]] 

means=  [0.607964   0.67222477 0.49199616 0.63164436 0.42555571 0.54599407
 0.45822107 0.64780601 0.52736862 0.36033761] 

array after mean  [[0.83925279 0.56811061 0.76086462 0.15980631 0.71178566]
 [0.90192488 0.77950678 0.80074812 0.11522967 0.76371438]
 [0.61653176 0.53831009 0.5015355  0.00733768 0.79626574]
 [0.98553605 0.99392451 0.13801976 0.14372778 0.89701369]
 [0.7190047  0.74636379 0.23667757 0.0939886

17. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [44]:
s =np.random.randint(0,10,(1,3))
t=np.random.randint(0,10,(3,1))
print(s, "\n")
print(t, "\n")
sums = []
for i in np.nditer(s):
    for j in np.nditer(t):
        sums.append(i+j)
print(np.array(sums).reshape(3,3))

[[2 3 5]] 

[[9]
 [6]
 [8]] 

[[11  8 10]
 [12  9 11]
 [14 11 13]]


18. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [48]:
u=np.arange(5,51,5)
print(u)
v=np.linspace(5,50,10)
print(v)

[ 5 10 15 20 25 30 35 40 45 50]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
