1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [2]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.16.5
<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


2. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49.

In [7]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. create two arrays and stack them vertically

In [13]:
b=np.random.randint(1,10,(2,2))
c=np.random.randint(11,22,(3,2))
d=np.vstack((b,c))
print(d)

[[ 5  3]
 [ 7  6]
 [15 19]
 [15 19]
 [17 20]]


5. Reverse a vector (first element becomes last).

In [19]:
e=np.arange(1,10)
f=np.flip(e)
print(e)
print(f)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [27]:
g=np.arange(0,9)
print(g)
g=np.reshape(g,(3,3))
print(g)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Find indices of non-zero elements from [1,2,0,0,4,0]

In [35]:
h=[1,2,0,0,4,0]
print("index of non zero element = ", end="")
for index,value in enumerate(h):
    if value!=0:
        print(index, end=",")

index of non zero element = 0,1,4,

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [43]:
k=np.random.randint(1,50,(10,10))
print(k)
print("max = ",np.amax(k))
print("min = ",np.amin(k))

[[40 45 46 34 14  3 42 21 18 46]
 [18 10 24 47 13 44  9 22 30  3]
 [ 4  5 22 15 38 42 17  1 36 48]
 [ 7  1 28  2 49  7 30 25 12 15]
 [13 36  8 31 36  8  1 10  8 44]
 [28 31 14 45 11 31 43 34 27 18]
 [15 27 32 48  6 13  7 10 47 20]
 [ 2 27 32 38 26 48  8 37 24 26]
 [ 4 19 49 37 41 27 28 26 46 11]
 [ 6 26 43 31 39 42 10  7 39 29]]
max =  49
min =  1


9. Create a random vector of size 30 and find the mean value.

In [37]:
i=np.arange(1,31)
print(i)
print(np.mean(i))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
15.5


10. Create a 2d array with 1 on the border and 0 inside


In [53]:
j=np.ones((5,5))
print(j)

j[1:-1,1:-1]=0
print(j)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


11. How to add a border (filled with 0's) around an existing array

In [60]:
k=np.ones((5,5))
np.pad(k, (1,1), mode = 'constant')

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

12. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [63]:
l=np.zeros((5,5))
for i in range(1,5):
    l[i][i-1]=i
print(l)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


13. Create a 5*5 matrix with random values and normalize it.