1. Create an array and find sum of it.

In [3]:
import numpy as np
a=np.arange(1,11)
print(a)
print(a.sum())

[ 1  2  3  4  5  6  7  8  9 10]
55


2. Find sin of given array.

In [9]:
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

[0.         0.5        0.70710678 0.8660254  1.        ]


3. Find mean of matrix along row and column.

In [14]:
b=np.random.randint(1,20,(3,3))
print(b, "\n")
print(np.mean(b, axis=1), "\n")
print(np.mean(b, axis=0))


[[12 13  5]
 [12 17 11]
 [17 13 10]] 

[10.         13.33333333 13.33333333] 

[13.66666667 14.33333333  8.66666667]


4. Find standard deviation of given array.

In [22]:
c=np.random.randint(2,23,(10,5))
print(c)
print(c.std(axis=0))
print(c.std(axis=1))

[[17  5 10 15 10]
 [ 4  7  7 14 10]
 [22 17  2  8 17]
 [ 3  3 13 16  9]
 [19 15 19 17  8]
 [19  2 14 21 13]
 [17 21  4  7  8]
 [ 8 17 18 17  6]
 [11  3 20  4  8]
 [ 8 17 16  8  8]]
[6.4776539  6.95772951 6.01747455 5.25452186 3.0016662 ]
[4.22374242 3.38230691 7.1944423  5.23067873 4.07921561 6.61513416
 6.46838465 5.11468474 6.11228272 4.1761226 ]


5. Create a 3*3 matrix and print it's transpose matrix

In [24]:
c=np.random.randint(2,23,(10,5))
print(c, "\n")
print(c.T)

[[15 20  9 21  8]
 [18  3  9 13 18]
 [13 18  9 10 10]
 [17  3 21  9 12]
 [21 15 18  7  8]
 [ 6  9 10 21  7]
 [ 4 14  6 15 20]
 [20 11 20  2  7]
 [22 16 15  4 20]
 [ 6  6 12 18  6]] 

[[15 18 13 17 21  6  4 20 22  6]
 [20  3 18  3 15  9 14 11 16  6]
 [ 9  9  9 21 18 10  6 20 15 12]
 [21 13 10  9  7 21 15  2  4 18]
 [ 8 18 10 12  8  7 20  7 20  6]]


6. Create an array of 3*3 and find index of max along both axis

In [29]:
d=np.random.randint(2,26,(3,3))
print(d)
print(d.argmax(axis=0))
print(d.argmax(axis=1))

[[ 3 25  3]
 [18 17 18]
 [25 18  3]]
[2 0 1]
[1 0 0]


7. find sum of two matrix.

In [33]:
e=np.random.randint(2,23,(3,3))
f=np.random.randint(4,24,(3,3))
print(e,"\n")
print(f,"\n")
print(e+f)

[[12  5 10]
 [11 20  4]
 [14  3  5]] 

[[ 8  4 13]
 [13 16 16]
 [14 21 14]] 

[[20  9 23]
 [24 36 20]
 [28 24 19]]


8. Find indexes of max element along axis=0 and axis=1 

In [35]:
g=np.random.randint(2,15,(4,4))
print(g)
print(g.argmax(axis=0))
print(g.argmax(axis=1))

[[13 13  9  4]
 [ 6  4 12  9]
 [ 5  4 11 11]
 [ 5 13 13  9]]
[0 0 3 2]
[0 2 2 1]


9. Write a program to add two arrays of different shape.

In [60]:
h=np.array((2,3,4,5,6,7))
i=np.array((9,8,7))
print(h+i[:,np.newaxis], "\n")
print(i.shape)
print(h[:, np.newaxis]+i)

[[11 12 13 14 15 16]
 [10 11 12 13 14 15]
 [ 9 10 11 12 13 14]] 

(3,)
[[11 10  9]
 [12 11 10]
 [13 12 11]
 [14 13 12]
 [15 14 13]
 [16 15 14]]


10. Try to solve a array and print a array with indices which would sort the given array.

In [66]:
j=np.random.randint(2,24,9)
print(j,"\n")
print(np.sort(j),"\n")
print(np.argsort(j))

[13 16  7 22  8  9 17 20 19] 

[ 7  8  9 13 16 17 19 20 22] 

[2 4 5 0 1 6 8 7 3]


11. Try to do perform same operation mentioned in previous questions for multidimentional array along both axis.

In [72]:
j=np.random.randint(2,24,(4,4))
print(j,"\n")
print(np.sort(j, axis=1),"\n")
print(np.sort(j, axis=0),"\n")

[[14  5 13 17]
 [19  2  9  5]
 [14 10  5 12]
 [ 5  9  5  4]] 

[[ 5 13 14 17]
 [ 2  5  9 19]
 [ 5 10 12 14]
 [ 4  5  5  9]] 

[[ 5  2  5  4]
 [14  5  5  5]
 [14  9  9 12]
 [19 10 13 17]] 



12. calculate multiplication of transpose and matrix itself of a 3*3 matrix.

In [78]:
k=np.random.randint(1,10,(3,3))
l=k.T
print(k, "\n")
print(l, "\n")
print(k*l)

[[9 2 7]
 [2 5 8]
 [9 4 9]] 

[[9 2 9]
 [2 5 4]
 [7 8 9]] 

[[81  4 63]
 [ 4 25 32]
 [63 32 81]]


13. Find solution for given linear equstion:

In [84]:
#2x + 5y = 28 4x + 3*y = 81
m=np.array(((2,5),(4,3)))
print(m,"\n")
n=np.array((28,81))
print(n, "\n")
print("solution = ", np.linalg.solve(m,n))

[[2 5]
 [4 3]] 

[28 81] 

solution =  [22.92857143 -3.57142857]


14. Find Rank, Trace, Inverse, Determinant of a given matrix

In [86]:
o=np.random.randint(5,25,(4,4))
o

array([[23, 12, 10, 18],
       [23, 24, 19, 17],
       [ 6, 22, 14,  5],
       [22,  6,  6, 13]])

In [89]:
print("rank = ", np.linalg.matrix_rank(o), "\n")
print("trace = ", np.trace(o), "\n")
print("Determinant = ", np.linalg.det(o), "\n")
print("inverse = ", np.linalg.inv(o))

rank =  4 

trace =  74 

Determinant =  3279.9999999999964 

inverse =  [[-0.12195122 -0.03902439  0.05487805  0.19878049]
 [ 0.15853659 -0.32926829  0.29115854  0.09908537]
 [-0.29268293  0.54634146 -0.39329268 -0.15792683]
 [ 0.26829268 -0.03414634 -0.04573171 -0.23231707]]


15. Find cube of a mtrix.

In [92]:
p=np.random.randint(6,27,(4,5))
print(p, "\n")
print(p*p*p)
print("\n")
print(np.power(p,3))

[[ 9  6  6 22 23]
 [ 7 11  9 23 13]
 [ 8 13 12 13 10]
 [13 13 17 13 24]] 

[[  729   216   216 10648 12167]
 [  343  1331   729 12167  2197]
 [  512  2197  1728  2197  1000]
 [ 2197  2197  4913  2197 13824]]


[[  729   216   216 10648 12167]
 [  343  1331   729 12167  2197]
 [  512  2197  1728  2197  1000]
 [ 2197  2197  4913  2197 13824]]
