1.Count the number of times each value appears in an array of integers.

In [2]:
import numpy as np
a=np.random.randint(1,8,15)
a

array([6, 5, 2, 3, 7, 6, 5, 4, 7, 6, 2, 6, 6, 3, 7])

In [23]:
b=np.unique(a, return_counts=True)
b

(array([1, 2, 3, 5, 6, 7]), array([3, 4, 1, 4, 2, 1], dtype=int64))

2. Given 9 integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [26]:
c=np.array((2,3,4,3,2,4,4,3,56))
print(c.reshape(3,3))

[[ 2  3  4]
 [ 3  2  4]
 [ 4  3 56]]


3. How to find the memory size of any array

In [29]:
d=np.random.randint(1,15,(5,5))
print(d)
print(d.nbytes)

[[13  3 14 11 11]
 [ 2  1  2  9 11]
 [ 3  9 10 12 10]
 [ 2  5  6 11  6]
 [ 2  2  3 10  6]]
100


4. Create a 2D array of size 10 by 10 with 1 on the border and 0 inside

In [41]:
e=np.zeros((8,8))

print(np.pad(e,1,'constant',constant_values=1))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. create a 8x8 matrix and fill it with a checkerboard pattern.

In [48]:
f=np.zeros((8,8))
f[1::2,::2]=1
f[0::2,1::2]=1
print(f)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
6. Normalize a 5x5 random matrix. 
normalization formula : ((a-mean(a))/std(a))
    

In [49]:
g=np.random.randint(2,22,(4,4))
print((g-np.mean(g))/np.std(a))

[[ 2.06414682 -4.83688136 -0.4005061  -3.35808961]
 [-2.86515902  0.58535507  4.52879975  0.58535507]
 [ 4.03586916 -2.86515902  1.57121624  1.07828565]
 [-2.86515902  4.03586916 -4.34395078  3.05000799]]


7.Given a 1D array in range (0,11), negate all elements which are between 3 and 8, in place

In [4]:
h=np.arange(0,11)
for val in h:
    if val>3 and val<8:
        h[val]=(-1)*val
print(h)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


8. How to get the dates of yesterday, today and tomorrow?

In [5]:
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)


Yesterday :  2020-02-17
Today :  2020-02-18
Tomorrow :  2020-02-19


9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [6]:
i=np.random.randint(10,25,(2,4))
j=np.random.randint(2,23,(3,3))
print(i-j)

ValueError: operands could not be broadcast together with shapes (2,4) (3,3) 

10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?

In [8]:
k=np.random.choice(['cat','dog','rat'],100)
k

array(['dog', 'rat', 'cat', 'rat', 'rat', 'rat', 'dog', 'rat', 'rat',
       'cat', 'cat', 'rat', 'rat', 'dog', 'dog', 'rat', 'dog', 'cat',
       'cat', 'dog', 'dog', 'cat', 'dog', 'cat', 'dog', 'cat', 'cat',
       'cat', 'dog', 'rat', 'dog', 'dog', 'cat', 'rat', 'cat', 'rat',
       'rat', 'dog', 'cat', 'dog', 'cat', 'dog', 'dog', 'cat', 'dog',
       'rat', 'dog', 'cat', 'dog', 'dog', 'rat', 'rat', 'dog', 'dog',
       'rat', 'dog', 'dog', 'cat', 'cat', 'rat', 'rat', 'dog', 'rat',
       'rat', 'rat', 'dog', 'dog', 'dog', 'rat', 'cat', 'dog', 'dog',
       'cat', 'cat', 'rat', 'rat', 'rat', 'rat', 'cat', 'rat', 'rat',
       'dog', 'rat', 'rat', 'rat', 'cat', 'rat', 'dog', 'dog', 'cat',
       'cat', 'cat', 'rat', 'dog', 'dog', 'dog', 'cat', 'dog', 'cat',
       'cat'], dtype='<U3')

11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values

In [9]:
l=np.random.random(10)
print(l)

[0.86365574 0.57782682 0.56844197 0.94489766 0.22086225 0.25139965
 0.04213915 0.54502192 0.70380058 0.08013807]


12. Given a two dimensional array, how to extract unique rows?

In [10]:
m=np.random.randint(1,100,(4,4))
m

array([[68, 66, 65, 39],
       [76, 68, 81,  3],
       [20, 59, 96, 74],
       [ 6,  2, 62,  9]])

In [12]:
count=1
for values in m:
    print("row {}= ".format(count),values)
    count+=1

row 1=  [68 66 65 39]
row 2=  [76 68 81  3]
row 3=  [20 59 96 74]
row 4=  [ 6  2 62  9]


13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

14. How to find the closest value (to a given scalar) in a vector?

In [15]:
scaler=int(input())
n=np.random.randint(12,69,12)
dif=abs(scaler-n[0])
new=n[0]
for val in n:
    if dif>abs(scaler-val):
        dif=(scaler-val)
        new=val
print(n)
print("closet val is {} to {}".format(dif,new))

34
[63 30 13 63 43 49 53 27 51 29 31 24]
closet val is 3 to 31


15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [18]:
import math
o=np.random.randint(10,50,(10,2))
print(o)


[[14 42]
 [19 31]
 [44 32]
 [17 11]
 [25 10]
 [22 39]
 [40 49]
 [41 15]
 [18 24]
 [34 16]]


In [19]:
for index in range(len(o)-1):
    dis=((o[index+1][1]-o[index][1])**2)-((o[index+1][0]-o[index][0])**2)
    dist=math.sqrt(abs(dis))
    print("distance between {} and {} is {}".format(o[index],o[index+1],dist))

distance between [14 42] and [19 31] is 9.797958971132712
distance between [19 31] and [44 32] is 24.979991993593593
distance between [44 32] and [17 11] is 16.97056274847714
distance between [17 11] and [25 10] is 7.937253933193772
distance between [25 10] and [22 39] is 28.844410203711913
distance between [22 39] and [40 49] is 14.966629547095765
distance between [40 49] and [41 15] is 33.98529093593286
distance between [41 15] and [18 24] is 21.166010488516726
distance between [18 24] and [34 16] is 13.856406460551018


16. How to sort an array by the nth column?

In [43]:
p=np.random.randint(10,50,(4,4))
print(p)
n=int(input("Enter the column to sort "))
print(p[p[:,n].argsort()])

[[40 43 49 39]
 [20 49 40 43]
 [20 17 44 14]
 [28 13 26 46]]
Enter the column to sort 1
[[28 13 26 46]
 [20 17 44 14]
 [40 43 49 39]
 [20 49 40 43]]


17.How to tell if a given 2D array has null columns?

In [68]:
o=np.array(([1,0,3],[6,0,0],[3,0,5],[6,0,8]))
for col in range(len(o.T)):
    if np.any(o[:,col]):
        print("zero column not found")
    else:
        p=(o[:,col])
        print("zero column found in column number {}".format(col))

zero column not found
zero column found in column number 1
zero column not found


18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [91]:
q=np.random.randint(10,50,(4,4))
print("original array: ","\n",q,"\n")
x=q[:,-1]+q[:,-2]
sums=x.reshape(4,1)
print("sum of last two array:","\n",sums,"\n")
q=np.delete(q,np.s_[2:],axis=1)
q=np.hstack((q,sums))
print("array after summing up the last two columns","\n",q)

original array:  
 [[12 34 48 34]
 [16 29 47 38]
 [27 33 36 25]
 [49 30 28 46]] 

sum of last two array: 
 [[82]
 [85]
 [61]
 [74]] 

array after summing up the last two columns 
 [[12 34 82]
 [16 29 85]
 [27 33 61]
 [49 30 74]]


19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

In [8]:
r=np.random.randint(10,26,(5,5))
print("original array:","\n",r)
for col in range(len(r.T)):
    r[:,col]+=col+1
print("after processing","\n",r)

original array: 
 [[13 17 22 11 18]
 [23 15 23 23 20]
 [20 16 10 20 24]
 [15 13 15 15 25]
 [18 25 17 11 13]]
after processing 
 [[14 19 25 15 23]
 [24 17 26 27 25]
 [21 18 13 24 29]
 [16 15 18 19 30]
 [19 27 20 15 18]]


20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [17]:
s=np.random.choice((True,False),size=100)
ans=np.unique(s, return_counts=True)
print("number of true's= ", ans[1][1])

number of true's=  54


21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [24]:
t=np.array([1,2,3,4,5])
index=1
while index<len(t):
    for i in range(3):
        t=np.insert(t,index,0)
    index+=4
print(t)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


22. How to swap two rows of an array?

In [5]:
u=np.random.randint(10,26,(5,5))
print("original array:", "\n",u)
u[[0, 2]] = u[[2, 0]]
print("interchanged array","\n",u)

original array: 
 [[13 18 16 25 20]
 [14 18 14 18 14]
 [23 23 12 12 18]
 [20 17 10 15 15]
 [21 18 24 21 21]]
interchanged array 
 [[23 23 12 12 18]
 [14 18 14 18 14]
 [13 18 16 25 20]
 [20 17 10 15 15]
 [21 18 24 21 21]]


23. How to get n largest value of an array?

In [6]:
v=np.random.randint(10,26,(5,5))
print("array",'\n',v)
print(np.amax(v))

array 
 [[14 13 23 20 18]
 [10 16 18 23 15]
 [20 16 25 17 14]
 [10 14 10 13 15]
 [11 15 16 25 18]]
25


24. Given two random arrays of shape 5X5, identify the common elements between them.

In [11]:
w=np.random.randint(10,26,(5,5))
x=np.random.randint(10,26,(5,5))
print("first array= :","\n",w,"\n","second array= ","\n",x,"\n","common elements= ","\n",np.intersect1d(w,x))

first array= : 
 [[24 22 16 10 20]
 [23 11 13 11 24]
 [15 18 19 17 15]
 [25 21 25 13 25]
 [19 12 10 25 15]] 
 second array=  
 [[23 24 24 12 15]
 [12 10 15 11 20]
 [25 10 11 18 25]
 [15 20 15 17 11]
 [23 14 12 11 12]] 
 common elements=  
 [10 11 12 15 17 18 20 23 24 25]


25. How to get index of top two highest value in a 1d array?

In [16]:
y=np.random.randint(10,266,200)
print("array", y)
max_val=y[0]
max_index=0
second_max=y[1]
second_index=1
for index,val in enumerate(y):
    if max_val<val:
        max_val=val
        max_index=index
print("highest value is: ",max_val,"at",max_index)
for index,val in enumerate(y):
    if index!=max_index:
        if second_max<val:
            second_max=val
            second_index=index
print("second highest value is: ", second_max,"at ",second_index)

array [134 236  77 161  58 209 216  10 242 101 193 201 150  78 174 162 177 136
  77  13 206 225 141 262 128  29 239 153 108 121 179  41  58 208  58 190
 234 198  24 141  29  94  42  30 232 108 243 107 144  94 162  64 251  70
  38 210  25  83 234 209 126  69 205  39 173  19  30 165  80 216 144  82
 124 240  75 105 183 251 130 169  55 257 248 200 110 237 135 254 170  84
  52 255  93 189  88  66  37  67 129 258 137  86 264  58  20 126  73  56
 198 218 123 246 169 164 157 151 214 121 199 113 134 254  48 152 102  32
 202 189  25 123 156 234  22 110  72  73 215 260 160 164  13 229  86  79
 156  66 240  46 213  34  63 239  90  95 186 221 133 102 217 171  62 248
  14  54 243 239 200  16 223  47 257 227 239 207 125 170  33 110 107  90
 190  34 146 206 173 137 187 158 211 130  74 247 167 178  49 151 226 140
  42 179]
highest value is:  264 at 102
second highest value is:  262 at  23
